services:
  postgres:
    image: postgres:17

    environment:
      POSTGRES_DB: quest
      POSTGRES_USER: quest
      POSTGRES_PASSWORD: quest

    ports:
      - "5432:5432"

    volumes:
      - quest_postgres_data:/var/lib/postgresql/data

volumes:
  quest_postgres_data: