spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

app.upload-dir=${UPLOAD_DIR}

server.address=127.0.0.1
server.port=8080

server.forward-headers-strategy=framework

server.servlet.session.cookie.secure=true
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax

server.error.include-message=never
server.error.include-stacktrace=never