spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/quest}
spring.datasource.username=${DB_USER:quest}
spring.datasource.password=${DB_PASSWORD:quest}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true